# Changes here will be overwritten by Copier
_commit: 37f89c1
_src_path: https://github.com/python-project-templates/base.git
add_docs: false
add_extension: python
add_wiki: false
email: t.paine154@gmail.com
github: python-project-templates
project_description: pydantic models to argparse CLIs
project_name: p2a
python_version_primary: '3.11'
team: the p2a authors
